import type { CompanyProfile, DataRoom, ScanResponses, TrackerTask } from "./types";

export const demoCompanies: CompanyProfile[] = [
  {
    id: "constructora-sur",
    name: "Constructora del Sur SpA",
    industry: "Construcción / Inmobiliaria",
    city: "Temuco",
    size: "51-200",
    monthlyRevenue: "$80M-$250M CLP",
    channels: ["Meta Ads", "web", "portales", "WhatsApp", "referidos"],
    tools: ["Google Sheets", "WhatsApp Business", "Meta Ads", "email"],
    team: ["gerencia comercial", "5 ejecutivos", "marketing externo", "administración"],
    mainProblem:
      "Llegan leads desde portales, Meta Ads y referidos, pero el seguimiento depende del ejecutivo. Hay baja trazabilidad entre consulta, financiamiento, visita, cotización y reserva.",
    digitalMaturity: "Sistema en desarrollo",
    metrics: {
      monthlyLeads: 420,
      responseTime: "5 horas",
      unfollowedLeads: "38%",
      leadToVisit: "12%",
      visitToReservation: "8%",
      salesCycle: "45-90 días",
    },
  },
  {
    id: "clinica-aurora",
    name: "Clínica Aurora",
    industry: "Clínica / salud / estética / dental",
    city: "Santiago",
    size: "11-50",
    channels: ["Instagram", "WhatsApp", "web", "referidos"],
    tools: ["agenda manual", "WhatsApp Business", "Instagram", "Google Calendar"],
    team: ["directora", "recepción", "especialistas", "marketing"],
    mainProblem:
      "WhatsApp está saturado, la agenda depende de recepción, los pacientes preguntan mucho pero no todos agendan, y no existe seguimiento postconsulta.",
    digitalMaturity: "Alto riesgo",
    metrics: {
      monthlyInquiries: 900,
      responseTime: "3 horas",
      unfollowedInquiries: "31%",
      inquiryToBooking: "18%",
      noShow: "14%",
    },
  },
  {
    id: "automotora-andes",
    name: "Automotora Andes",
    industry: "Automotora",
    city: "Temuco",
    size: "51-200",
    channels: ["web", "Meta Ads", "Google Ads", "WhatsApp", "llamadas"],
    tools: ["CRM", "WhatsApp Business", "email", "planillas"],
    team: ["jefe de ventas", "8 vendedores", "financiamiento", "servicio técnico"],
    mainProblem:
      "Los leads llegan por modelos, financiamiento, permuta y campañas, pero no existe un SLA único de asignación ni seguimiento. Cada vendedor responde distinto.",
    digitalMaturity: "Sistema en desarrollo",
    metrics: {
      monthlyLeads: 650,
      responseTime: "4 horas",
      unfollowedLeads: "29%",
      testDriveRate: "9%",
      closeRate: "4%",
    },
  },
  {
    id: "legal-montt",
    name: "Estudio Legal Montt & Asociados",
    industry: "Legal",
    city: "Puerto Montt",
    size: "11-50",
    channels: ["web", "referidos", "WhatsApp", "LinkedIn"],
    tools: ["email", "Google Drive", "planillas", "agenda"],
    team: ["socios", "abogados", "asistente legal", "administración"],
    mainProblem:
      "Las consultas entran por web, WhatsApp y referidos. No hay clasificación inicial clara, se piden documentos tarde y se pierden oportunidades por falta de intake.",
    digitalMaturity: "Alto riesgo",
    metrics: {
      monthlyInquiries: 180,
      responseTime: "9 horas",
      unfollowedInquiries: "24%",
      inquiryToMeeting: "16%",
      meetingToContract: "22%",
    },
  },
  {
    id: "mercado-vivo",
    name: "Pyme Local Mercado Vivo",
    industry: "Pyme local",
    city: "Temuco",
    size: "1-10",
    channels: ["Instagram", "WhatsApp", "tienda física"],
    tools: ["Instagram", "WhatsApp", "cuaderno", "transferencias"],
    team: ["dueña", "2 vendedoras"],
    mainProblem:
      "La dueña responde, vende, publica, cobra y atiende. Hay clientes que preguntan por WhatsApp y no vuelven. No existe base de clientes ni campañas de recompra.",
    digitalMaturity: "Fuga crítica",
    metrics: {
      monthlyInquiries: 260,
      responseTime: "7 horas",
      unfollowedInquiries: "45%",
      estimatedRepurchase: "12%",
    },
  },
  {
    id: "century-sur-brokers",
    name: "Century Sur Brokers",
    industry: "Corredores de propiedades / Brokerage inmobiliario",
    city: "Chile, red nacional demo",
    size: "201-500 agentes asociados",
    model: "Red de oficinas y corredores independientes",
    channels: ["web corporativa", "portales inmobiliarios", "referidos", "WhatsApp", "Instagram", "llamadas", "oficinas físicas"],
    tools: ["CRM inmobiliario", "WhatsApp Business", "planillas", "email", "calendario", "portales"],
    team: ["dirección nacional", "líderes de oficina", "corredores", "asistentes comerciales", "marketing", "administración"],
    mainProblem:
      "La red recibe oportunidades de compradores, propietarios y referidos, pero cada corredor trabaja con sus propios hábitos. Hay baja visibilidad sobre velocidad de respuesta, seguimiento de compradores, captación de propiedades, visitas realizadas, ofertas emitidas y oportunidades dormidas.",
    digitalMaturity: "Sistema en desarrollo",
    metrics: {
      activeAgents: 280,
      offices: 18,
      buyerLeads: 2400,
      ownerLeads: 620,
      capturedProperties: 310,
      scheduledVisits: 1100,
      offersIssued: 180,
      responseTime: "6 horas",
      unfollowedAfter72h: "42%",
      unclassifiedBuyers: "48%",
      ownersNoPostValuationFollowUp: "35%",
      propertiesWithoutCommercialPlan: "29%",
      buyerLeadToVisit: "11%",
      visitToOffer: "7%",
      offerToClose: "18%",
    },
  },
];

export const demoCompany = demoCompanies[0];

export const demoResponsesByCompany: Record<string, ScanResponses> = {
  "constructora-sur": {
    sales: [2, 2, 3, 2, 2],
    marketing: [3, 2, 2, 2, 3],
    customer: [3, 2, 2, 2, 2],
    operations: [2, 3, 2, 2, 2],
    technology: [2, 2, 2, 1, 2],
    team: [3, 2, 2, 2, 2],
    leadership: [3, 2, 2, 2, 2],
    experience: [3, 2, 2, 2, 2],
    aiReadiness: [2, 2, 1, 2, 1],
    continuousImprovement: [2, 2, 2, 2, 2],
    inbox: [2, 2, 1, 2, 2, 2, 2, 2],
  },
  "clinica-aurora": {
    sales: [2, 2, 2, 2, 2],
    marketing: [3, 2, 2, 2, 2],
    customer: [2, 2, 3, 2, 2],
    operations: [2, 2, 2, 1, 2],
    technology: [2, 1, 2, 1, 1],
    team: [2, 2, 2, 2, 2],
    leadership: [2, 2, 2, 2, 2],
    experience: [2, 2, 2, 2, 1],
    aiReadiness: [1, 2, 1, 1, 1],
    continuousImprovement: [2, 1, 2, 2, 1],
    inbox: [2, 2, 1, 2, 2, 1, 2, 2],
  },
  "automotora-andes": {
    sales: [2, 2, 3, 2, 2],
    marketing: [3, 2, 2, 3, 2],
    customer: [2, 2, 2, 2, 2],
    operations: [3, 2, 2, 2, 2],
    technology: [3, 2, 2, 2, 2],
    team: [3, 2, 2, 2, 2],
    leadership: [3, 2, 2, 2, 2],
    experience: [3, 2, 2, 2, 2],
    aiReadiness: [2, 2, 1, 2, 1],
    continuousImprovement: [2, 2, 2, 2, 2],
    inbox: [2, 2, 2, 2, 2, 2, 2, 2],
  },
  "legal-montt": {
    sales: [2, 2, 2, 2, 2],
    marketing: [2, 2, 1, 2, 2],
    customer: [2, 2, 2, 2, 2],
    operations: [2, 2, 2, 1, 2],
    technology: [2, 1, 2, 1, 1],
    team: [2, 2, 2, 2, 2],
    leadership: [2, 2, 2, 2, 2],
    experience: [2, 2, 2, 2, 2],
    aiReadiness: [1, 2, 1, 1, 1],
    continuousImprovement: [2, 1, 2, 2, 1],
    inbox: [2, 2, 1, 2, 2, 2, 2, 1],
  },
  "mercado-vivo": {
    sales: [1, 2, 1, 1, 1],
    marketing: [2, 1, 1, 1, 1],
    customer: [2, 2, 1, 1, 1],
    operations: [1, 1, 1, 1, 1],
    technology: [1, 1, 1, 1, 1],
    team: [2, 1, 1, 1, 1],
    leadership: [2, 1, 1, 1, 1],
    experience: [2, 1, 1, 1, 1],
    aiReadiness: [1, 1, 1, 1, 1],
    continuousImprovement: [1, 1, 1, 1, 1],
    inbox: [1, 1, 1, 1, 1, 1, 1, 1],
  },
  "century-sur-brokers": {
    sales: [2, 2, 3, 2, 2],
    marketing: [3, 2, 2, 2, 2],
    customer: [2, 2, 2, 2, 2],
    operations: [2, 2, 2, 2, 2],
    technology: [3, 2, 2, 2, 2],
    team: [3, 2, 2, 2, 2],
    leadership: [3, 2, 2, 2, 2],
    experience: [2, 2, 2, 2, 2],
    aiReadiness: [2, 2, 2, 2, 1],
    continuousImprovement: [2, 2, 2, 2, 2],
    inbox: [2, 2, 2, 2, 2, 2, 2, 2],
  },
};

export const demoResponses = demoResponsesByCompany["constructora-sur"];

export function createDataRoom(company: CompanyProfile): DataRoom {
  const responseTime = company.metrics.responseTime ?? "4 horas";
  const unfollowed = company.metrics.unfollowedLeads ?? company.metrics.unfollowedInquiries ?? company.metrics.unfollowedAfter72h ?? "30%";

  return {
    leads: {
      leadsMensuales: company.metrics.monthlyLeads ?? company.metrics.monthlyInquiries ?? company.metrics.buyerLeads ?? 420,
      consultasMensuales: company.metrics.monthlyInquiries ?? company.metrics.monthlyLeads ?? company.metrics.buyerLeads ?? 420,
      tiempoPromedioRespuesta: responseTime,
      porcentajeSinSeguimiento: unfollowed,
      canalesPrincipales: company.channels,
      objecionesFrecuentes: ["precio", "tiempo", "confianza", "comparación"],
      etapaDondeMasSePierden: "seguimiento posterior al primer contacto",
    },
    sales: {
      ventasMensuales: company.monthlyRevenue ?? "No informado",
      ticketPromedio: "Variable por industria",
      cicloDeVenta: company.metrics.salesCycle ?? "14-45 días",
      tasaDeCierre: company.metrics.closeRate ?? company.metrics.offerToClose ?? "No medida",
      cantidadDeVendedores: company.metrics.activeAgents ?? 5,
      etapasPipeline: ["entrada", "clasificación", "seguimiento", "propuesta", "cierre"],
      kpiPrincipal: "oportunidades con próxima acción",
    },
    communication: {
      tonoMarca: "claro, humano y experto",
      mensajesFrecuentes: ["primer contacto", "retoma", "objeción de precio", "confirmación"],
      preguntasFrecuentes: ["precio", "disponibilidad", "plazos", "documentos", "siguiente paso"],
      scriptsExistentes: "informales",
      canalesAtencion: company.channels,
      consistenciaMensaje: "media/baja",
    },
    operations: {
      procesosCriticos: ["asignación", "seguimiento", "registro", "revisión semanal"],
      tareasRepetitivas: ["responder consultas", "recordar próximos pasos", "actualizar estado"],
      herramientasUsadas: company.tools,
      responsables: company.team,
      cuellosDeBotella: ["WhatsApp", "memoria individual", "datos dispersos"],
      dependenciaPersonaClave: "alta",
    },
    team: {
      roles: company.team,
      responsables: company.team,
      nivelEntrenamiento: "heterogéneo",
      reunionesSeguimiento: "informales",
      cargaOperativa: "alta",
      problemasCoordinacion: ["prioridades", "seguimiento", "registro de aprendizajes"],
    },
    files: [
      { name: "CSV de leads", status: "Analizado demo" },
      { name: "Historial de WhatsApp", status: "Cargado" },
      { name: "Documento de procesos", status: "Pendiente" },
      { name: "Guiones de venta", status: "Pendiente" },
      { name: "Preguntas frecuentes", status: "Analizado demo" },
      { name: "Reporte comercial", status: "Cargado" },
      { name: "Base de clientes", status: "Cargado" },
    ],
    benchmarks: [
      "Tu tiempo de respuesta supera la ventana recomendada para leads calientes.",
      "Tu porcentaje de leads sin seguimiento sugiere fuga comercial crítica.",
      "Tu operación depende de herramientas no conectadas.",
      "Tu equipo no tiene suficientes rituales de mejora.",
    ],
    brokerage:
      company.industry === "Corredores de propiedades / Brokerage inmobiliario"
        ? {
            buyers: {
              leadsCompradoresMensuales: 2400,
              compradoresClasificados: "52%",
              presupuestoPromedio: "$110M CLP",
              comunasMasSolicitadas: ["Temuco", "Santiago", "Puerto Varas", "Concepción"],
              urgenciaCompra: "media/alta",
              visitasAgendadas: 1100,
              visitasRealizadas: 860,
              ofertasEmitidas: 180,
            },
            owners: {
              propietariosContactados: 620,
              tasacionesRealizadas: 410,
              propiedadesCaptadas: 310,
              propiedadesPublicadas: 286,
              propiedadesSinMovimiento: "29%",
              seguimientoPostTasacion: "65%",
            },
            agents: {
              numeroCorredores: 280,
              leadsPorCorredor: 9,
              respuestaPromedioPorCorredor: "6 horas",
              proximasAccionesRegistradas: "54%",
              oportunidadesDormidas: 840,
              reunionesPipeline: "irregulares por oficina",
            },
            offices: {
              numeroOficinas: 18,
              leadsPorOficina: 133,
              conversionPorOficina: "variable",
              lideresOficina: 18,
              alertasPorOficina: 11,
            },
          }
        : undefined,
  };
}

export const demoDataRooms: Record<string, DataRoom> = Object.fromEntries(
  demoCompanies.map((company) => [company.id, createDataRoom(company)]),
) as Record<string, DataRoom>;

export const demoTrackerTasks: TrackerTask[] = [
  {
    id: "task-1",
    title: "Crear SLA de respuesta a leads calientes.",
    description: "Definir tiempo máximo, responsable y alerta para primer contacto.",
    area: "Ventas",
    origin: "Bridge Flow™",
    priority: "Alta",
    owner: "Coordinación comercial",
    status: "Pendiente",
    suggestedDate: "72 horas",
    kpi: "tiempo de primera respuesta",
    expectedImpact: "menos oportunidades dormidas",
    difficulty: "Media",
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-2",
    title: "Clasificar oportunidades sin próxima acción.",
    description: "Revisar oportunidades abiertas y asignar etapa, responsable y siguiente paso.",
    area: "Operaciones",
    origin: "Data Room",
    priority: "Alta",
    owner: "Líder de área",
    status: "En progreso",
    suggestedDate: "7 días",
    kpi: "oportunidades con próxima acción",
    expectedImpact: "mayor trazabilidad y foco",
    difficulty: "Media",
    createdAt: new Date().toISOString(),
  },
];
