import type { DemoIndustry, IndustryRules } from "./types";

const baseRules: IndustryRules = {
  benchmarkWarnings: [
    "Herramientas instaladas no equivalen a procesos vivos.",
    "La IA requiere datos conectados, workflows claros y revisión humana.",
    "La velocidad de respuesta afecta fuertemente la calificación de oportunidades.",
  ],
  typicalLeaks: ["seguimiento irregular", "datos dispersos", "mensajes inconsistentes", "decisiones sin dueño"],
  kpisToWatch: ["tiempo respuesta", "oportunidades sin seguimiento", "conversión por canal", "próxima acción"],
  recommendedAutomations: ["alerta de oportunidad sin respuesta", "secuencia 7 días", "resumen semanal"],
  recommendedScripts: ["primer contacto", "retoma", "mensaje interno de seguimiento"],
  academyLessons: ["Responder leads con claridad", "Seguimiento sin parecer insistente", "Cómo documentar un proceso simple"],
  executiveLanguage:
    "El problema no suele ser la falta de herramientas, sino la falta de visibilidad sobre qué ocurre entre contacto, responsable, seguimiento y medición.",
  riskSignals: ["más de 25% sin seguimiento", "respuesta superior a 1 hora", "muchos datos registrados sin próxima acción"],
  opportunitySignals: ["demanda existente", "canales activos", "equipo con conocimiento práctico", "procesos repetibles"],
};

export const industryRules: Record<DemoIndustry, IndustryRules> = {
  "Construcción / Inmobiliaria": {
    ...baseRules,
    typicalLeaks: [
      "leads por proyecto sin priorización",
      "baja trazabilidad de financiamiento",
      "seguimiento irregular después de cotización",
      "poca coordinación entre marketing, ventas y disponibilidad real",
    ],
    kpisToWatch: ["lead a visita", "visita a reserva", "tiempo respuesta", "leads sin contacto", "leads por proyecto"],
    recommendedAutomations: [
      "asignación automática por proyecto",
      "alerta de lead sin respuesta",
      "secuencia de seguimiento 7/14/30 días",
      "actualización automática de disponibilidad",
    ],
    recommendedScripts: ["primer contacto interesado en proyecto", "retoma de lead dormido", "solicitud de datos para financiamiento"],
    academyLessons: ["Cómo priorizar leads inmobiliarios", "Cómo hacer seguimiento sin parecer insistente", "Cómo medir visitas por canal"],
    executiveLanguage:
      "En proyectos inmobiliarios, la fuga aparece cuando marketing genera demanda pero ventas no logra trazabilidad entre consulta, financiamiento, visita, cotización y reserva.",
  },
  Automotora: {
    ...baseRules,
    typicalLeaks: ["leads no asignados en minutos", "seguimiento irregular por vendedor", "mensajes distintos por modelo", "baja conexión entre venta y financiamiento", "pérdida de leads por permuta"],
    kpisToWatch: ["tiempo asignación", "cotización a test drive", "test drive a venta", "leads por modelo", "leads por vendedor"],
    recommendedAutomations: ["asignación inmediata", "secuencia 7 días", "alerta lead caliente", "script por intención: financiamiento, permuta, flota, cotización"],
    recommendedScripts: ["primer contacto por modelo", "retoma por financiamiento", "mensaje de prueba de manejo"],
    academyLessons: ["Clasificar intención automotriz", "Seguimiento por modelo", "Medir desempeño por vendedor sin fricción"],
    executiveLanguage:
      "La automotora no pierde solo por precio; pierde cuando intención, modelo, financiamiento, permuta y próximo paso no quedan visibles para el equipo.",
  },
  "Clínica / salud / estética / dental": {
    ...baseRules,
    typicalLeaks: ["WhatsApp saturado", "pacientes sin confirmación", "no-shows", "objeciones de precio mal manejadas", "ausencia de seguimiento postconsulta"],
    kpisToWatch: ["consulta a agenda", "agenda a asistencia", "no-show", "seguimiento postconsulta", "recompra / control"],
    recommendedAutomations: ["confirmación 24h", "recordatorio 3h", "seguimiento 24h post atención", "respuestas base por tratamiento"],
    recommendedScripts: ["primer contacto paciente", "confirmación de agenda", "seguimiento postconsulta"],
    academyLessons: ["Cómo reducir no-shows", "Responder dudas sin saturar recepción", "Educar antes de agendar"],
    executiveLanguage:
      "En salud y estética, la fuga no está solo en la agenda; aparece entre consulta, educación, confirmación, asistencia y seguimiento posterior.",
  },
  Legal: {
    ...baseRules,
    typicalLeaks: ["intake sin clasificación", "documentos pedidos tarde", "consultas urgentes sin priorización", "seguimiento posterior débil"],
    kpisToWatch: ["consulta a reunión", "reunión a contrato", "tiempo respuesta", "casos por área", "documentos pendientes"],
    recommendedAutomations: ["formulario de intake", "checklist por tipo de caso", "recordatorio de documentos", "secuencia de seguimiento"],
    recommendedScripts: ["primer contacto legal", "solicitud de documentos", "retoma de consulta urgente"],
    academyLessons: ["Cómo clasificar consultas legales", "Intake con menos fricción", "Seguimiento profesional sin presión"],
    executiveLanguage:
      "En servicios legales, la oportunidad se pierde cuando la urgencia no se clasifica, los documentos llegan tarde y nadie ve el estado real del intake.",
  },
  "Pyme local": {
    ...baseRules,
    typicalLeaks: ["consultas sin registro", "clientes antiguos no reactivados", "promociones sin calendario", "ventas dependen de la dueña"],
    kpisToWatch: ["consultas por canal", "respuesta promedio", "recompra", "ventas por campaña"],
    recommendedAutomations: ["base simple de clientes", "mensaje de retoma", "calendario de promoción", "seguimiento postcompra"],
    recommendedScripts: ["primer contacto WhatsApp", "reactivación cliente antiguo", "postcompra humano"],
    academyLessons: ["WhatsApp como proceso", "Recompra simple", "Orden semanal para negocios locales"],
    executiveLanguage:
      "La pyme no necesita más complejidad; necesita sacar la operación de la memoria de la dueña y convertir ventas, atención y recompra en hábitos visibles.",
  },
  "Corredores de propiedades / Brokerage inmobiliario": {
    benchmarkWarnings: [
      "Más de 25% de leads sin seguimiento después de 72 horas indica riesgo comercial alto.",
      "Tiempo de respuesta superior a 1 hora en leads calientes reduce visibilidad de intención real.",
      "Un CRM inmobiliario sin próxima acción registrada funciona como archivo, no como sistema comercial.",
    ],
    typicalLeaks: [
      "compradores sin clasificación por intención, presupuesto, comuna o urgencia",
      "propietarios captados sin seguimiento después de tasación",
      "corredores que responden tarde por estar en visitas",
      "oportunidades dormidas en CRM o WhatsApp",
      "mensajes distintos entre corredores",
      "propiedades publicadas sin plan comercial",
      "visitas realizadas sin seguimiento posterior",
      "ofertas no registradas o no empujadas",
      "baja visibilidad de desempeño por corredor",
      "falta de ritual semanal de pipeline",
      "leads de portales mezclados con referidos sin prioridad",
      "dependencia de agenda personal del corredor",
      "falta de scripts para captación, retoma y cierre",
    ],
    kpisToWatch: [
      "tiempo de primera respuesta",
      "leads compradores asignados por corredor",
      "compradores clasificados",
      "propiedades captadas",
      "tasaciones realizadas",
      "visitas agendadas",
      "visitas sin seguimiento",
      "ofertas emitidas",
      "cierre por corredor",
      "propiedades sin movimiento",
      "oportunidades dormidas 7/14/30 días",
      "tasa lead a visita",
      "tasa visita a oferta",
      "tasa oferta a cierre",
      "seguimiento post tasación",
      "seguimiento post visita",
    ],
    recommendedAutomations: [
      "asignación automática de lead comprador por zona, tipo de propiedad o disponibilidad del agente",
      "alerta inmediata cuando un lead no recibe respuesta en 15 minutos",
      "secuencia de seguimiento comprador 1, 3, 7, 14 y 30 días",
      "secuencia de seguimiento propietario después de tasación",
      "recordatorio post visita a las 3 horas y 24 horas",
      "alerta de propiedad sin movimiento en 14 días",
      "clasificación automática de comprador por presupuesto, comuna, urgencia y tipo de propiedad",
      "tablero de oportunidades dormidas",
      "resumen semanal por oficina",
      "ranking saludable de hábitos comerciales por corredor",
      "alertas a líder de oficina cuando un corredor acumula leads sin seguimiento",
    ],
    recommendedScripts: [
      "Primer contacto comprador: Hola, [Nombre], soy [Corredor] de [Oficina]. Vi que consultaste por [Propiedad/Zona]. Para ayudarte mejor, ¿estás buscando para comprar pronto, evaluar opciones o comparar financiamiento? Te puedo enviar 2 o 3 alternativas similares hoy.",
      "Retoma comprador dormido: Hola, [Nombre]. Te escribo porque hace unos días consultaste por propiedades en [Zona]. Vi que hay nuevas opciones que podrían calzar con lo que buscabas. ¿Sigues mirando alternativas o ya encontraste algo?",
      "Seguimiento post visita: Hola, [Nombre]. Gracias por visitar la propiedad. Para ayudarte a decidir, ¿qué fue lo que más te gustó y qué duda te quedó pendiente?",
      "Captación propietario: Hola, [Nombre]. Para ayudarte a vender mejor, no basta con publicar la propiedad. Necesitamos definir precio, estrategia de difusión, perfil de comprador y seguimiento.",
      "Seguimiento post tasación: Hola, [Nombre]. Ya revisamos el valor estimado y el comportamiento del mercado. El siguiente paso sería definir si buscamos velocidad de venta, mejor precio o una estrategia equilibrada.",
      "Mensaje interno líder de oficina: Equipo, esta semana revisaremos tres indicadores: leads sin respuesta, visitas sin seguimiento y propiedades sin movimiento.",
    ],
    academyLessons: [
      "Cómo responder leads inmobiliarios en menos de 15 minutos",
      "Cómo clasificar compradores por intención real",
      "Cómo hacer seguimiento sin parecer insistente",
      "Cómo captar propietarios con estrategia",
      "Cómo dar seguimiento después de una visita",
      "Cómo trabajar oportunidades dormidas",
      "Cómo medir desempeño comercial sin competencia tóxica",
      "Cómo usar WhatsApp como proceso y no como caos",
      "Cómo crear un ritual semanal de pipeline inmobiliario",
      "Cómo convertir referidos en sistema comercial",
    ],
    executiveLanguage:
      "El problema de una red de corredores no suele ser la falta de oportunidades. El problema suele estar en la falta de visibilidad sobre qué ocurre después del primer contacto: quién respondió, quién clasificó, quién agendó visita, quién hizo seguimiento, quién pidió oferta y qué oportunidades quedaron dormidas.",
    riskSignals: [
      "más de 25% de leads sin seguimiento después de 72 horas",
      "tiempo de respuesta superior a 1 hora en leads calientes",
      "compradores sin clasificación",
      "propietarios sin seguimiento post tasación",
      "propiedades sin movimiento en 14 días",
      "visitas sin seguimiento posterior",
      "baja conversión visita a oferta",
      "corredores sin rutina semanal de pipeline",
      "muchos leads registrados, pero pocos con próxima acción",
      "alta dependencia de WhatsApp personal",
    ],
    opportunitySignals: [
      "leads entrantes desde portales con alta intención",
      "red de corredores con cobertura territorial",
      "propiedades captadas sin plan comercial",
      "referidos que pueden sistematizarse",
      "compradores que no compraron una propiedad, pero siguen activos",
      "propietarios que pidieron tasación y no recibieron seguimiento",
      "datos de CRM que pueden convertirse en hábitos comerciales",
      "líderes de oficina que podrían usar dashboards de mejora",
    ],
  },
  Educación: baseRules,
  "Municipalidad / institución pública": baseRules,
  "Retail / e-commerce": baseRules,
  Logística: baseRules,
  "Hotelería / turismo": baseRules,
  "Gimnasio / wellness": baseRules,
  "Energía / estaciones de servicio / conveniencia": baseRules,
};

export function getIndustryRules(industry: DemoIndustry): IndustryRules {
  return industryRules[industry] ?? baseRules;
}
