import type { IntegrationItem } from "./types";

export const whatsappEnterpriseInstall = {
  title: "WhatsApp Business Platform / Cloud API",
  summary:
    "Conexión enterprise para leer eventos de conversaciones, estados, archivos y tiempos de respuesta mediante webhooks y convertirlos en tareas, alertas y oportunidades accionables.",
  requirements: [
    "Meta Business Manager verificado o administrado por el cliente.",
    "WhatsApp Business Account asociado a la empresa.",
    "Número empresarial autorizado para Cloud API.",
    "App de Meta con permisos y webhook HTTPS.",
    "Plantillas aprobadas para mensajes iniciados por la empresa.",
    "Política interna de privacidad, retención y uso de datos.",
  ],
  reads: [
    "mensajes entrantes",
    "estados de entrega",
    "media IDs / archivos",
    "número o identificador del contacto",
    "timestamp de conversación",
    "plantillas utilizadas",
    "eventos de webhook",
  ],
  activates: [
    "crear conversación en Bridge Inbox™",
    "asignar responsable",
    "medir SLA de primera respuesta",
    "detectar conversación sin próxima acción",
    "crear tarea en Bridge Flow™",
    "levantar alerta en Bridge Pulse™",
    "sugerir script aprobado por etapa",
  ],
  implementationSteps: [
    "Confirmar si el cliente usará número existente o número nuevo.",
    "Crear o validar WhatsApp Business Account en Meta.",
    "Configurar Cloud API y obtener phone_number_id.",
    "Crear endpoint webhook en The Bridge System™.",
    "Verificar webhook y suscribir eventos de mensajes.",
    "Crear plantillas de utilidad para confirmación, seguimiento y documentos.",
    "Mapear estados Bridge Inbox™: nuevo lead, seguimiento pendiente, documento pendiente, cliente dormido.",
    "Probar flujo con sandbox antes de producción.",
  ],
};

export const integrationCatalog: IntegrationItem[] = [
  {
    name: "HubSpot",
    category: "CRM",
    status: "Disponible",
    reads: ["contactos", "deals", "etapas", "actividades", "motivos de pérdida"],
    actions: ["crear tarea", "actualizar etapa", "activar secuencia", "alertar lead dormido"],
    expectedImpact: "CRM usado como sistema vivo, no solo base de datos.",
    difficulty: "Media",
    nextAction: "Mapear etapas reales del pipeline y campos mínimos.",
  },
  {
    name: "Zoho CRM",
    category: "CRM",
    status: "Disponible",
    reads: ["leads", "cuentas", "propietarios", "actividades", "campos personalizados"],
    actions: ["asignar responsable", "crear próxima acción", "alertar oportunidad sin seguimiento"],
    expectedImpact: "Más trazabilidad comercial por vendedor, oficina o unidad.",
    difficulty: "Media",
    nextAction: "Auditar calidad de datos y campos obligatorios.",
  },
  {
    name: "Pipedrive",
    category: "CRM",
    status: "Disponible",
    reads: ["deals", "pipeline", "actividades", "origen", "probabilidad"],
    actions: ["crear actividad", "mover etapa", "generar alerta de SLA"],
    expectedImpact: "Mejor disciplina de seguimiento y priorización.",
    difficulty: "Baja/Media",
    nextAction: "Definir qué etapa representa una fuga real.",
  },
  {
    name: "Salesforce",
    category: "CRM",
    status: "Requiere configuración",
    reads: ["leads", "opportunities", "accounts", "tasks", "campaigns"],
    actions: ["crear task", "actualizar opportunity", "enviar señal a líder"],
    expectedImpact: "Capa estratégica sobre equipos enterprise con muchos datos.",
    difficulty: "Alta",
    nextAction: "Definir alcance por objeto y permisos.",
  },
  {
    name: "WhatsApp Business",
    category: "WhatsApp",
    status: "Preparado para integración",
    reads: ["mensajes entrantes", "etiquetas", "responsables", "tiempos de respuesta", "archivos", "conversaciones abiertas"],
    actions: ["crear alertas", "generar tareas", "sugerir scripts", "activar recordatorios", "levantar reportes", "detectar oportunidades dormidas"],
    expectedImpact: "Convertir WhatsApp en parte del sistema operativo de la empresa, sin reemplazarlo.",
    difficulty: "Media",
    nextAction: "Definir etiquetas base, responsables y reglas de próxima acción antes de conectar API.",
  },
  {
    name: "Google Sheets",
    category: "Analytics",
    status: "Conectado demo",
    reads: ["leads", "ventas", "responsables", "estados", "fechas"],
    actions: ["crear vista de fugas", "exportar tareas", "actualizar score demo"],
    expectedImpact: "Puente inicial para empresas sin CRM maduro.",
    difficulty: "Baja",
    nextAction: "Estandarizar columnas mínimas.",
  },
  {
    name: "Meta Ads",
    category: "Ads",
    status: "Disponible",
    reads: ["campañas", "formularios", "origen", "costo por lead", "creativos"],
    actions: ["marcar campañas con baja conversión", "priorizar leads calientes"],
    expectedImpact: "Conectar inversión publicitaria con seguimiento real.",
    difficulty: "Media",
    nextAction: "Relacionar campaña con etapa comercial.",
  },
  {
    name: "Google Ads",
    category: "Ads",
    status: "Disponible",
    reads: ["campañas", "keywords", "conversiones", "costo"],
    actions: ["detectar intención alta", "activar alerta de contacto rápido"],
    expectedImpact: "Menos intención desperdiciada por respuesta tardía.",
    difficulty: "Media",
    nextAction: "Definir conversiones útiles para Bridge Score™.",
  },
  {
    name: "Google Analytics",
    category: "Analytics",
    status: "Disponible",
    reads: ["fuente", "eventos", "formularios", "rutas", "conversión"],
    actions: ["detectar fricción web", "priorizar páginas con caída"],
    expectedImpact: "Mejor lectura entre tráfico, intención y fuga.",
    difficulty: "Media",
    nextAction: "Configurar eventos clave.",
  },
  {
    name: "Systeme.io",
    category: "Formularios",
    status: "Disponible",
    reads: ["formularios", "embudos", "emails", "contactos"],
    actions: ["crear tarea de seguimiento", "segmentar por intención", "detectar abandono"],
    expectedImpact: "Conectar embudos simples con operación comercial.",
    difficulty: "Baja/Media",
    nextAction: "Definir campos y etiquetas de entrada.",
  },
  {
    name: "Odoo",
    category: "ERP",
    status: "Requiere configuración",
    reads: ["clientes", "ventas", "inventario", "proyectos", "facturas"],
    actions: ["levantar alertas operativas", "conectar ventas con ejecución"],
    expectedImpact: "Visibilidad entre operación y dirección.",
    difficulty: "Alta",
    nextAction: "Auditar módulos activos.",
  },
  {
    name: "Softland",
    category: "ERP",
    status: "Próximamente",
    reads: ["clientes", "documentos", "ventas", "cobranza"],
    actions: ["señales de riesgo comercial", "alertas de proceso"],
    expectedImpact: "Conectar datos administrativos con decisiones.",
    difficulty: "Alta",
    nextAction: "Explorar API o exportaciones seguras.",
  },
  {
    name: "Defontana",
    category: "ERP",
    status: "Próximamente",
    reads: ["ventas", "clientes", "documentos", "productos"],
    actions: ["detectar oportunidades por historial", "alertar caída de recompra"],
    expectedImpact: "Mejor lectura de negocio para pymes y empresas medianas.",
    difficulty: "Media/Alta",
    nextAction: "Validar fuente de datos disponible.",
  },
  {
    name: "Webhooks",
    category: "API / Webhooks",
    status: "Disponible",
    reads: ["eventos externos", "formularios", "cambios de estado", "señales de canal"],
    actions: ["crear alerta", "actualizar Data Room", "disparar Bridge Flow™"],
    expectedImpact: "Arquitectura agéntica preparada para integraciones reales.",
    difficulty: "Media",
    nextAction: "Definir eventos de entrada y payload mínimo.",
  },
];
